name: byteformer
channels:
  - defaults
dependencies:
  - python=3.10
  - pip=24.0
  - pip:
      - --extra-index-url=https://download.pytorch.org/whl/cu121
      - -r corenet/requirements.txt
      - -e ./corenet
